cli-sdk: write errors to log file (#753)
This PR implements an error log file that will be written for unhandled
errors and some of the handled ones where it would be helpful to be able
to inspect the entire nested error cause chain including all the stack
traces. This is written to `XDG('vlt/error-logs').data()`.

Here's an example of an unhandled error. By default all unhandled errors
get the error log and link to open an issue.

```
╰❯ vlt_local_node query ':bork'
Error: Unsupported pseudo-class: :bork

Full details written to: /Users/lukekarrys/.local/data/vlt/error-logs/error-85886.log

Open an issue with the full error details at:
  https://github.com/vltpkg/vltpkg/issues/new

╰❯ cat /Users/lukekarrys/.local/data/vlt/error-logs/error-85886.log
Error: Unsupported pseudo-class: :bork
    at pseudo (file:///Users/lukekarrys/projects/vltpkg/vltpkg/src/query/src/pseudo.ts:354:11)
    at async walk (file:///Users/lukekarrys/projects/vltpkg/vltpkg/src/query/src/index.ts:92:11)
    at async walk (file:///Users/lukekarrys/projects/vltpkg/vltpkg/src/query/src/index.ts:115:17)
    at async walk (file:///Users/lukekarrys/projects/vltpkg/vltpkg/src/query/src/index.ts:115:17)
    at async Query.search (file:///Users/lukekarrys/projects/vltpkg/vltpkg/src/query/src/index.ts:432:25)
    at async command (file:///Users/lukekarrys/projects/vltpkg/vltpkg/src/cli-sdk/src/commands/query.ts:150:28)
    at async outputCommand (file:///Users/lukekarrys/projects/vltpkg/vltpkg/src/cli-sdk/src/output.ts:150:33)
    at async Module.run (file:///Users/lukekarrys/projects/vltpkg/vltpkg/src/cli-sdk/src/index.ts:114:3)
    at async run (file:///Users/lukekarrys/projects/vltpkg/vltpkg/infra/build/src/bins.ts:30:5)
    at async file:///Users/lukekarrys/projects/vltpkg/vltpkg/infra/build/src/bins/vlt.ts:2:1 {
  [cause]: {
    found: <ref *1> Pseudo {
      value: ':bork',
      source: { start: { line: 1, column: 1 }, end: { line: 1, column: 5 } },
      sourceIndex: 0,
      spaces: { before: '', after: '' },
      nodes: [],
      type: 'pseudo',
      parent: <ref *2> Selector {
        source: { start: { line: 1, column: 1 }, end: { line: 1, column: 5 } },
        sourceIndex: 0,
        spaces: { before: '', after: '' },
        nodes: [ [Circular *1] ],
        type: 'selector',
        parent: Root {
          source: {
            start: { line: 1, column: 1 },
            end: { line: 1, column: 5 }
          },
          spaces: { before: '', after: '' },
          nodes: [ [Circular *2] ],
          type: 'root',
          _error: [Function (anonymous)],
          lastEach: 1,
          indexes: {}
        },
        lastEach: 1,
        indexes: {}
      }
    }
  }
}
```

Some handled errors like `EREQUEST` still get an error log but will not
link to open a new issue. This is because there are some relevant top
level error details to provide but it can still be helpful to inspect
the full error.

```
╰❯ vlt_local_node i react --registry=https://localhost:9999
build⠋ > actual > reify
1 requests
Request Error: Request failed
  Code: ECONNREFUSED
  URL: https://localhost:9999/react
  Method: GET

Full details written to: /Users/lukekarrys/.local/data/vlt/error-logs/error-86024.log

╰❯ cat /Users/lukekarrys/.local/data/vlt/error-logs/error-86024.log
Error: Request failed
    at RegistryClient.request (file:///Users/lukekarrys/projects/vltpkg/vltpkg/src/registry-client/src/index.ts:484:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async PackageInfoClient.packument (file:///Users/lukekarrys/projects/vltpkg/vltpkg/src/package-info/src/index.ts:572:26)
    at async PackageInfoClient.manifest (file:///Users/lukekarrys/projects/vltpkg/vltpkg/src/package-info/src/index.ts:422:11)
    at async file:///Users/lukekarrys/projects/vltpkg/vltpkg/src/graph/src/ideal/append-nodes.ts:93:20
    at async Promise.all (index 0)
    at async appendNodes (file:///Users/lukekarrys/projects/vltpkg/vltpkg/src/graph/src/ideal/append-nodes.ts:82:3)
    at async addNodes (file:///Users/lukekarrys/projects/vltpkg/vltpkg/src/graph/src/ideal/add-nodes.ts:59:5)
    at async buildIdealFromStartingGraph (file:///Users/lukekarrys/projects/vltpkg/vltpkg/src/graph/src/ideal/build-ideal-from-starting-graph.ts:56:3)
    at async build (file:///Users/lukekarrys/projects/vltpkg/vltpkg/src/graph/src/ideal/build.ts:70:15) {
  [cause]: {
    code: 'EREQUEST',
    cause: AggregateError [ECONNREFUSED]:
        at internalConnectMultiple (node:net:1139:18)
        at afterConnectMultiple (node:net:1714:7) {
      code: 'ECONNREFUSED',
      cause: { code: 'ECONNREFUSED' },
      [errors]: [
        Error: connect ECONNREFUSED ::1:9999
            at createConnectionError (node:net:1677:14)
            at afterConnectMultiple (node:net:1707:16) {
          errno: -61,
          code: 'ECONNREFUSED',
          syscall: 'connect',
          address: '::1',
          port: 9999
        },
        Error: connect ECONNREFUSED 127.0.0.1:9999
            at createConnectionError (node:net:1677:14)
            at afterConnectMultiple (node:net:1707:16) {
          errno: -61,
          code: 'ECONNREFUSED',
          syscall: 'connect',
          address: '127.0.0.1',
          port: 9999
        }
      ]
    },
    url: URL {
      href: 'https://localhost:9999/react',
      origin: 'https://localhost:9999',
      protocol: 'https:',
      username: '',
      password: '',
      host: 'localhost:9999',
      hostname: 'localhost',
      port: '9999',
      pathname: '/react',
      search: '',
      searchParams: URLSearchParams {},
      hash: ''
    },
    method: 'GET'
  }
}
```

Other handled errors like `EUSAGE` don't benefit from an error log or
bug report so we skip writing those, and the output remains the same as
it was before.

```
╰❯ vlt_local_node pkg gett
Usage:
  vlt pkg [<command>] [<args>]

Get or manipulate package.json values

  Subcommands

    get
      Get a single value

      vlt pkg get [<key>]

    init
      Initialize a new package.json file in the current directory

      vlt pkg init

    pick
      Get multiple values or the entire package

      vlt pkg pick [<key> [<key> ...]]

    set
      Set one or more key value pairs

      vlt pkg set <key>=<value> [<key>=<value> ...]

    delete
      Delete one or more keys from the package

      vlt pkg delete <key> [<key> ...]

  Examples

    Set a value on an object inside an array

    vlt pkg set "array[1].key=value"

    Append a value to an array

    vlt pkg set "array[]=value"

Usage Error: Unrecognized pkg command
  Found: gett
  Valid options: get, set, rm
```


---

This PR also separates the concerns of creating errors and converting
unknown values to printable errors.

`@vltpkg/error-cause` is now only concerned with generating errors as it
was originally.

`@vltpkg/output` now has exports for parsing `unknown` values into a
root error. There are also ways to optionally rethrow if nothing
printable is found and match a root error based on a code.

It is helpful to separate these because while it is tempting to have
type guards that live in `error-cause` for checking if something is one
of “our” errors, we can never really know because all fields are
optional and every value passed to a catch block is unknown by design.
There are other options like branding our errors but that seems like
overkill. And this way lets us treat all thrown values the same by using
runtime value checking instead of type guards.

This change also moves a few utility type guards to `@vltpkg/types`. I
don’t feel great about this package being a dumping ground for utils but
they are already used across many workspaces and it makes more sense for
them to live there than in `error-cause` I think.