cli-sdk(run, exec): add --query support (#837)
This PR adds a `--query` flag to the config definitions and uses it
inside `exec-command.ts` which is used across `run`, `run-exec`, `exec`
and `exec-local`.

When run with `--query`, the graph will be loaded and the query will be
used to find all nodes that both match the query *and* are importers.
Then the list of importer paths will be passed directly to
`Monorepo.load`.

That means this does not allow for running scripts in nodes other than
importers. This can seem weird at times where `vlt query $QUERY` will
return a result but `vlr --query $QUERY` will not match any importers.
Here's an example:

```sh
╰❯ vlt query '#typescript'
vlt_workspaces_2025-06-06-10-30
└── typescript@5.8.3
a
└── typescript@5.6.3
b
└── typescript@5.7.3

╰❯ vlr --query '#typescript' test
Error: no matching workspaces found

Full details written to: /Users/lukekarrys/.local/data/vlt/error-logs/error-63374.log

Open an issue with the full error details at:
  https://github.com/vltpkg/vltpkg/issues/new
```

But it does unlock queries that would match an importer such as `#id`:

```sh
╰❯ vlr --query '#a'
Scripts available: { name: 'echo a' }
```

---

One side effect of this change is that undici's
`Dispatcher.RequestOptions` also has a `query` option which conflicts
with the one in config definitions. Since we pass along `conf.options`
directly in a few places, those callers needed to explicitly overwrite
`query: undefined`.

---

Refs: https://github.com/vltpkg/statusboard/issues/169