registry-client: update to undici@7 (#544)
@darcyclarke reported a deno crash with the following stack:

```
error: Uncaught TypeError: fastNowTimeout.refresh is not a function
       fastNowTimeout.refresh();
                     ^
at refreshTimeout (file:///var/folders/gd/1pffxr4d603251w7w1q_cb_40000gn/T/deno-compile-vlt/chunk-06ZDSGAE.js:1863:24)
at onTick (file:///var/folders/gd/1pffxr4d603251w7w1q_cb_40000gn/T/deno-compile-vlt/chunk-06ZDSGAE.js: 1858:9)
at callback (ext: deno_web/02_timers. js:58:7)
at eventLoopTick (ext:core/01_core.js:212:13)
```

This code lives in undici, so I think updating undici to the latest
version will make it easier to triage future bugs/crashes like this.