cli-sdk: add expect-results config
Add a new `--expect-results` config value that when used with the
`vlt query` command allows for validation of the result values of
a query.

Example:

    vlt query --expect-results=">=1"
    my-project
    └── a@1.0.0

    vlt query --expect-results=false
    Error: Unexpected number of items
        at ...
      [cause]: { found: 1, wanted: 0 }
    }

Fixes: https://github.com/vltpkg/vltpkg/issues/592