spec: fix missing catalog config error msg (#1300)
When a `catalog:` is in use in a `package.json` file but haven't been
properly configured the error message prints an helpful error message:

    Error: Named catalog not found

Instead of:

    TypeError: Cannot convert undefined or null to object